#!/bin/bash

# ref https://wiki.archlinux.org/title/Internet_sharing

# Cleanup function to kill processes
cleanup() {
    echo "Cleaning up..."
    killall dnsmasq
    killall hostapd
    echo "Cleanup complete."
}

# Trap signals to ensure cleanup runs
trap cleanup EXIT INT TERM

# Usage: ./initSoftAP <wireless_interface> <internet_interface>
if [ $# -ne 2 ]; then
  echo "Usage: $0 <wireless_interface> <internet_interface>"
  exit 1
fi

###########
echo "Initiate wifi interface configuration: $1..."
ip link set $1 down
ip addr flush dev $1
ip link set $1 up
ip addr add 192.168.5.1/24 dev $1

# If you still use ifconfig for some reason, replace the above lines with the
# ifconfig $1 up 192.168.5.1 netmask 255.255.255.0

sleep 3

##########
echo "Starting dnsmasq..."
if [ -z "$(ps -e | grep dnsmasq)" ]; then
 dnsmasq
fi

#########
######### Enable NAT ##########
echo "Configuring iptables..."
iptables -t nat -A POSTROUTING -o $2 -j MASQUERADE
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $1 -o $2 -j ACCEPT
# Uncomment the line below if facing problems while sharing PPPoE
#iptables -t mangle -A FORWARD -o ppp0 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

######## Enable IPv4 packet forwarding ########
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv4.conf.all.forwarding=1
sysctl -w net.ipv6.conf.all.forwarding=1

#########
echo "Starting hostap..."
hostapd /etc/hostapd/hostapd.conf

if [ $? -ne 0 ]; then
  echo "Failed to start hostapd. Check /etc/hostapd.conf and ensure $1 supports AP mode."
  exit 1
fi

echo "SoftAP setup complete."
